### ISSUE TITLE
Could not find a version that satisfies the requirement pydra-mrtrix3

### ISSUE THREAD

**Issue by aswinnarayanan** [Australian-Imaging-Service/arcana#2]
Tried `pip install .` from arcana2 directory on Python 3.10.0 (linux)

pydra-mrtrix3 doesn't install 
`ERROR: Could not find a version that satisfies the requirement pydra-mrtrix3 (from arcana2[dev]) (from versions: none)`

Removing pydra-mrtrix3, allows installation to go through successfully
pydra-dcm2niix working fine

**Comment by tclose** [comment]
Need to publish pydra-mrtrix3 on PyPI. Will let you know when this is done

**Comment by tclose** [comment]
A version of pydra-mtrix3 is now available on PyPI, which resolves this issue
