### ISSUE TITLE
Implement autodocs

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/arcana#38]
As described at https://arcana.readthedocs.io/en/develop/deployment.html#autodocs, need to implement `arcana deploy docs` sub-command to automatically generate pipeline documentation from the pipeline YAML configurations.

**Comment by tclose** [comment]
@Prepultrue I have updated the document generation to match the refactoring of the YAML specs. Could you please check to see whether it is all working now?

**Comment by Prepultrue** [comment]
#74 and Australian-Imaging-Service/pipelines-core#10 should get things working.
