### ISSUE TITLE
Convert JSON edits syntax to use JQuery

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/arcana#78]
Instead of using a bespoke query language for editing JSON files in the `json_edits` feature of the `Bids` data store @Prepultrue suggested using JQuery. Would be nice to do it without adding a non-python dependency to the project, although it is not a dealbreaker

**Comment by Prepultrue** [comment]
[pyjq](https://github.com/doloopwhile/pyjq) essentially compiles `jq` as a library during install, and does not require it to be installed separately.

**Comment by tclose** [comment]
That's cool

**Comment by tclose** [comment]
Epic: Australian-Imaging-Service/pipelines#33

**Comment by tclose** [comment]
This has been implemented by https://github.com/Australian-Imaging-Service/arcana/pull/92
