### ISSUE TITLE
[STORY] Add unittest to cover doc generation

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/arcana#91]
### Description

As a developer, I want to be able to make changes to the Arcana code base without breaking the auto-generation of the pipeline docs used in the pipelines repo

### Acceptance Criteria

- [x] unittest that covers arcana.cli.deploy.build_docs

**Comment by Prepultrue** [comment]
In a similar vein, it would be good to add some warnings when a workflow config contains unexpected keys.

**Comment by tclose** [comment]
currently, the signature of the `build_xnat_cs_image` function that provides error checking for the build process but I could inspect the signature and include it in the `load_yaml_spec`

**Comment by tclose** [comment]
#33

**Comment by Prepultrue** [comment]
https://github.com/Australian-Imaging-Service/arcana/pull/107
